### ISSUE TITLE
Strange sequencer-as-gate behavior with custom envelope

### ISSUE THREAD

**Issue by bennlich** [colinbdclark/Flocking#141]
Try running this modified version of the Custom Envelope example: https://gist.github.com/bennlich/7971669a74526247d3c9

I hear three dramatic increases in volume, not following any obvious time scale. I'd expect to hear three repetitions of a 0.5s increase followed by a 0.5s decrease in volume (as specified in `customEnvelope`).

**Comment by bennlich** [comment]
Seeing similar behavior if you replace the gate in http://flockingjs.org/next/demos/playground/#asr with this sequencer:

```
var gateDef = {
  ugen: "flock.ugen.sequencer",
  durations: [1, 1, 1],
  values: [1, 1, 1],
  options: {
    resetOnNext: true
  }
};
```

**Comment by bennlich** [comment]
In [the sequencer example](http://flockingjs.org/next/demos/playground/#sequencer), something related seems to happen if you change the first value in the envelope times array from 0.03 to 0.003.

**NOTE: Do not use headphones when testing this! It gets very loud very fast!**

**Comment by colinbdclark** [comment]
Thanks for the detailed reports, @bennlich. I'll take a look as soon as I can. Hope your ears survived the bug-triaging process!

**Comment by colinbdclark** [comment]
The issue with the awful distortion in your last example, @bennlich, was a nasty and stupid bug in <code>flock.ugen.envGen</code> where it was endlessly incrementing the output value without ever moving on to the next envelope stage to due a bug where we weren't rounding durations when converting from seconds to samples. I've fixed this in cea1861.

**Comment by colinbdclark** [comment]
The issue in your first example, in addition to the above-mentioned bug, has to do with the fact that you're running your <code>flock.ugen.sequencer</code> at audio rate while the <code>flock.ugen.envGen</code> is running at control rate. If you change your envelope generator to run at audio rate, or your sequencer to run at control rate, it sounds as you expected it should.

I believe that there is some special casing in the sequencer when the <code>resetOnNext</code> option is used, ensuring that the correct reset behaviour occurs depending on whether the unit generator is running at control rather than audio rate. Unfortunately, in practice, this is somewhat brittle. Since your envelope generator is running at control rate, it's only reading the first value of the sequencer's output block (which will always be <code>1<code>), and thus the gate is never closing.

In the long run, I will need to rethink this <code>resetOnNext</code> option (though it is very convenient). In the short term, users will need to be aware of the fact that <code>flock.ugen.sequencer</code>s must be run at the same rate as the unit generator they are sequencing.

**Comment by bennlich** [comment]
Wow awesome! Thanks for looking into this so quickly!

> The issue with the awful distortion in your last example, @bennlich, was a nasty and stupid bug in flock.ugen.envGen where it was endlessly incrementing the output value without ever moving on to the next envelope stage to due a bug where we weren't rounding durations when converting from seconds to samples.

How did you ever figure this out? (And more generally, how in the world does one go about debugging audio synthesis software?) Were you able to recognize that the envelope generator wasn't switching stages, and then decide to stick a breakpoint somewhere in there?

**Comment by colinbdclark** [comment]
My first step in debugging this was just to wrap the whole tree of unit generators in a <code>flock.ugen.print</code> unit generator to print its output. From this, I was able to see that the amplitude was wildly growing.

At that point, I wrapped only the <code>flock.ugen.sequencer</code> in a <code>print</code> ugen and noticed that its output looked totally sane. I continued this process until I saw that the envelope was outputting really large values. So I then stuck a breakpoint in the <code>arGen()</code> function of the <code>flock.ugen.envGen</code> unit generator and stepped through until I noticed that it wasn't switching stages correctly due to the unrounded <code>numSegmentSamples</code> value.

That's generally my method for debugging. Use <code>flock.ugen.print</code> to sanity check the output of things,  then stick breakpoints in to inspect the raw input and output buffers, then step through the code.

Some day, when the [graphical playground](http://flockingjs.org/next/demos/playground/live/) is more robust, I can imagine that it'll have a debugging mode where each of the ugen nodes actually prints out its values in the GUI, so you'll be able to see (either via little scopes embedded in each node, or numerically) what the output signal of a unit generator is doing. It could be really cool.

**Comment by bennlich** [comment]
> The issue in your first example, in addition to the above-mentioned bug, has to do with the fact that you're running your flock.ugen.sequencer at audio rate while the flock.ugen.envGen is running at control rate. If you change your envelope generator to run at audio rate, or your sequencer to run at control rate, it sounds as you expected it should.

Verified!

> In the long run, I will need to rethink this resetOnNext option (though it is very convenient). In the short term, users will need to be aware of the fact that flock.ugen.sequencers must be run at the same rate as the unit generator they are sequencing

It also seems to sound as expected if the `flock.ugen.envGen` is running at audio rate while the sequencer is running at control rate. I only hear an issue when the `envGen` is at control rate, and the sequencer is at audio rate.
