### ISSUE TITLE
Can a bus be used in flock.ugen.in before it's defined in flock.ugen.out?

### ISSUE THREAD

**Issue by AlexNisnevich** [colinbdclark/Flocking#146]
Let's say I have two synths, with one modulating the other's frequency:

```
var pin5square = flock.synth({
  synthDef: {
    ugen: "flock.ugen.out",
    bus: 7,
    sources: {
      id: "pin5square",
      ugen: "flock.ugen.squareOsc",
      freq: 1,
      mul: 0.4,
    }
  }
});

var pin3sin = flock.synth({
  synthDef: {
    ugen: "flock.ugen.out",
    bus: 3,
    sources: {
      id: "pin3sin",
      ugen: "flock.ugen.sinOsc",
      freq: {
        ugen: "flock.ugen.value",
        rate: "audio",
        value: 440,
        mul: {
          ugen: "flock.ugen.in",
          bus: 5,
          add: 1
        }
      },
      mul: 0.3
    }
  }
});
```

This example works, but if I switch the order of the synth definitions, the sin wave is no longer modulated by the square wave.

I'm trying to make a JavaScript patchboard modular synth (similar to the Synthi A: http://www.thesynthi.de/data/SYNTHIA/A2011_1.jpg) at https://github.com/AlexNisnevich/synthi-js , and I need to be able to arbitrarily hook up the outputs of synths as the inputs of other synths. However, it appears that right now it's impossible to, for example, sometimes have synth A modulate synth B and sometimes have synth B modulate synth A (and even potentially have them modulate each other), at least the way I'm doing it.

Any ideas? 

P.S. Thanks for the awesome library!

**Comment by colinbdclark** [comment]
Cool, I'd love to hear your synth when it's done!

You can use the <code>addToEnvironment</code> option when you're creating a synth to control its position within the Flocking Environment's list of nodes. There is a section that outlines this option in the [Creating Synths](https://github.com/colinbdclark/Flocking/blob/78afbf846e37f2167774ccf98fcdacf4c8997542/docs/synths/creating-synths.md#addtoenvironment) documentation.

If you want to change the order of nodes dynamically after they've been created, you can use the <code>flock.nodeListComponent</code> API, which the Flocking environment object implements. These methods let you manipulate the evaluation order of your synths in various ways, including <code>head(node)</code>, <code>tail(node)</code>, <code>before(otherNode, node)</code>, <code>after(otherNode, node)</code>, <code>insert(index, node)</code>, <code>remove(node)</code>, and <code>replace(newNode, oldNode)</code>.

If you've moved onto the master branch of Flocking, these methods have been refactored a bit, but you can look at the [source documentation](https://github.com/colinbdclark/Flocking/blob/master/src/core.js#L1091-L1149) to see the API changes.

I hope this helps!

**Comment by AlexNisnevich** [comment]
Thanks, that works!

**Comment by colinbdclark** [comment]
Glad it worked for you. Let me know when your synth is available to play with. It seems like an extremely cool project!

**Comment by AlexNisnevich** [comment]
Hey @colinbdclark , just wanted to announce that I finally finished my [SYNTHI-JS emulator](https://github.com/AlexNisnevich/synthi-js)! Thank you so much for a great library - I couldn't have done this without Flocking.

**Comment by colinbdclark** [comment]
@AlexNisnevich This is so awesome! I'm super impressed—such a cool synth! I'll tweet about it from the flockingjs Twitter account.

**Comment by AlexNisnevich** [comment]
Thank you for the kind words! I'm glad you like it 😄

**Comment by AlexNisnevich** [comment]
Actually, I have one more issue I wanted to ask about:

SYNTHI-JS produces some audio buzz whenever any of the UI elements are interacted with (i.e. whenever a knob is turned). The buzzing is consistent and always present, and easy to reproduce (for example, connect pin A-1 to output sound, then try turning any knob – even one that has nothing to with the sound being produced!)

The buzzing occurs in both Safari and Chrome. Interestingly, it doesn't seem to occur in Firefox, but instead in Firefox there's a significant delay (about 500ms) between UI interactions and changes in the output produced. I suspect that these two issues are symptoms of the same underlying cause, but I don't know enough about the internals of Flocking or Web Audio to be able to diagnose it. I'm guessing is that DOM changes somehow "interrupt" the audio stream, but I'm not sure how.

It's not a critical issue – SYNTHI-JS is still usable as-is – but it would be great if I had some way to reduce the buzzing or remove it entirely.

**Comment by colinbdclark** [comment]
Yes, that was one of the first things I noticed too. The issue is somewhat systemic to Flocking's architecture at the moment, due to limitations in the Web Audio API. In short, all your unit generators are running in the main browser thread, the same place where your UI controls are running. This means that DOM manipulation or other expensive responses user actions risks interrupting the sound generation process. An upcoming update to the Web Audio API will allow Flocking to run its custom unit generators and signal processors in a separate, real-time process.

In the meantime, there are two approaches to fixing this issue: First, I'm working on introducing support for the Web Audio API's native nodes, which already run in a separate thread (but are much less configurable). That's going to take some time, but it's a major priority since this is a real weakness of Flocking for applications with complex user interfaces, such as yours.

On your end, you can adjust the buffer size of Flocking to make your synths more resilient to dropouts caused by user interaction. You'll probably want to play with different buffer sizes, trading off latency (the time it takes for the sound to adjust to the UI interactions) with lack of dropouts.

By default, Flocking uses a 2048-sample buffer on Firefox (since it tends to be prone to more dropouts due to its single-process architecture) and 1024 samples on other desktop browsers. That should translate to 46 and 23 ms of latency at 44.1KHz, respectively. How is it with, say, a 4096-sample buffer?

To adjust Flocking's latency, you can specify the <code>bufferSize</code> option in your call to <code>flock.init()</code>.

**Comment by colinbdclark** [comment]
I cloned the Synthi-js repository and spent a couple of minutes taking a look at the dropouts you're experiencing. It sounds like a 4K buffer size seems to help a lot, at the cost of stair-stepping as the knob is turned. Not ideal, but definitely better than crackles and dropouts.

Looking at it in the profiler, your code is spending a good amount of time in knobKnob's various event handlers. I think you could probably see some improvements by tightening up its code, attempting to reduce the amount of DOM manipulation and styling it does and by caching values rather than continually retrieving them from <code>localStorage</code> or re-selecting DOM elements with jQuery. Most costly, I think, is the repeated [DOM manipulation required to update the text labels for your frequency knobs](https://github.com/AlexNisnevich/synthi-js/blob/master/js/ui.js#L23).

These are all issues that will be moot when we can get Flocking's sample-generation pipeline out of the main thread, but at least there are some strategies to help mitigate it.
