### ISSUE TITLE
Playground not working on iOS 9.3.1

### ISSUE THREAD

**Issue by hamoid** [colinbdclark/Flocking#173]
I have tried on an iPad and the playground is silent.

I haven't checked the code, so I may be wrong, but sound should be enabled on "touchend".
It seems to work by add this:

```document.addEventListener("touchend", startMySound, false);```

and in startMySound I both .init() and .start() Flocking.

**Comment by colinbdclark** [comment]
Yes, you're right. This definitely seems to be a regression in iOS at some point. Thanks for noting the workaround. I'll take a look!

**Comment by colinbdclark** [comment]
This issue appears to be due to two issues:

1. Apple seems to have removed the <code>stop()</code> method from <code>AudioBufferSourceNode</code>, yet [Flocking's iOS initialization strategy](https://github.com/colinbdclark/Flocking/blob/master/src/web/output-manager.js#L179) uses it. 
2. In the master branch (version 0.1.x is unaffected), an Infusion IoC reference to Flocking's <code>ScriptProcessorNode</code> instance is incorrect, causing it to be undefined when initializing on iOS.

**Comment by colinbdclark** [comment]
Fixes for this issue have been pushed to master and the 0.1.x branch. I've cut a minor 0.1.6 maintenance release from the 0.1.x branch. Upgrading should resolve the issue causing Flocking not to work on iOS.
