### ISSUE TITLE
Add the ability to send messages to a MIDI device.

### ISSUE THREAD

**Issue by the-t-in-rtf** [colinbdclark/Flocking#217]
Currently, [`flock.midi.connection.send`](https://github.com/colinbdclark/Flocking/blob/442b68754f5154294c8303265ba9e969a05e781c/src/web/midi.js#L513) is set to call `flock.fail` with an error message.  I have put together a branch that adds write support and a demo harness for the same.  I will submit a PR once I add a few tests.

**Comment by colinbdclark** [comment]
This will be awesome, @the-t-in-rtf! I have just recently merged my #214 branch, which ensures that all of Flocking's unit tests run well in both Node.js and across supported browsers. So whenever you have time (no rush) to make a pull request against master, I'll be keen to review it.

**Comment by the-t-in-rtf** [comment]
I just realised that I can (and should) at least create unit tests that roundtrip between raw MIDI and JSON using the two encoding decoding functions.  I'll comment when that's ready.

**Comment by colinbdclark** [comment]
Yes, good point. One suggestion I was thinking of is to record some examples of MIDI output using MIDI Monitor or a similar tool, and then write your tests so that they verify that Flocking can produce the same raw messages. I have quite a number of [tests like this in osc.js](https://github.com/colinbdclark/osc.js/blob/master/tests/osc-tests.js#L695-L709), where I ended up having to hand-create raw OSC bytes in order to test both its reading and writing functionality. In the case of MIDI it should be a lot simpler, you can just sit down at your favourite controller or sequencer and grab examples of the kind of output you need to test with.

Round-trip tests are good too, definitely. But if we have some sample raw MIDI bytes we can test both sides of the system separately from the other, avoiding potential bugs that emerge from incorrect assumptions that are implemented consistently on both sides of the conversion process.

**Comment by colinbdclark** [comment]
Fixed via #224 and #237. Thanks again, @the-t-in-rtf!
